#!/usr/bin/env bash

bundle exec jekyll build

sha=`git rev-parse HEAD`
base=`date +"%Y-%m-%d"`
item=`echo "$base/$sha"`
echo $item

cd ..
git clone https://github.com/jboss-outreach-ibot/gci-autodeploy.git

mkdir -p gci-autodeploy/$item
cp -a gci/_site/. gci-autodeploy/$item/

cd gci-autodeploy
git config --local user.name "jboss-outreach-ibot"
git config --local user.email "anuj.garg@codingblocks.com"
git add .
git commit -m "Add commit for autodeploy"
git push --quiet "https://${BOT_USER}:${BOT_TOKEN}@github.com/jboss-outreach-ibot/gci-autodeploy.git" master

cd $item
ls -la
